#!/usr/bin/env bash

if [ -z $COMPOSE_FILE ]
then
    export COMPOSE_FILE=docker-compose-dev.yml
    echo "INFO: Environment variable COMPOSE_FILE is exported as $COMPOSE_FILE"
fi

docker-compose up & gulp watch
