FROM python:3.5

ENV PYTHONUNBUFFERED 1

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./compose/django/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh
RUN chmod +x /start-dev.sh

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y ruby rubygems-integration inotify-tools nodejs npm
RUN gem install sass -v 3.3.14

RUN ln -s /usr/bin/nodejs /usr/bin/node

WORKDIR /app

COPY . /app

RUN npm install

ENTRYPOINT ["/entrypoint.sh"]
