# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
