# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-22 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_presentation_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
