# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-10 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_presentation_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slide_order', models.PositiveSmallIntegerField()),
                ('markdown', models.TextField()),
                ('html', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='html',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='markdown',
        ),
        migrations.AddField(
            model_name='slide',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.Presentation'),
        ),
    ]
